# Generated by Django 3.2.6 on 2021-08-06 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imdb_id', models.CharField(max_length=48)),
                ('genres', models.CharField(max_length=200, null=True)),
                ('original_title', models.CharField(max_length=500)),
                ('overview', models.TextField(max_length=500, null=True)),
                ('vote_average', models.IntegerField(default=0)),
                ('poster_path', models.CharField(max_length=64, null=True)),
            ],
        ),
    ]
