# Generated by Django 3.2.6 on 2021-08-09 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movierecommender', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='recommended',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
