# Generated by Django 3.2.6 on 2021-08-06 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movierecommender', '0002_alter_movie_vote_average'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='watched',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
