# Generated by Django 3.2.6 on 2021-08-09 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movierecommender', '0002_movie_recommended'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='overview',
            field=models.TextField(max_length=2000, null=True),
        ),
    ]
